# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gork < Formula
  desc "ZORK I: The Great Underground Empire - Classic 1980s text adventure game ported to Go"
  homepage "https://github.com/wakatara/gork"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/gork/releases/download/0.1.8/gork_Darwin_x86_64.tar.gz"
      sha256 "5fc789b94af43a9a468d551c1327e2e436ceed8cf682c7fb48bcc21b4b3e1df0"

      def install
        bin.install "gork"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/gork/releases/download/0.1.8/gork_Darwin_arm64.tar.gz"
      sha256 "1801944651f38b33778e6d161900cc40d0642959bd2a79ce2bed05287841a0c3"

      def install
        bin.install "gork"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/gork/releases/download/0.1.8/gork_Linux_x86_64.tar.gz"
      sha256 "a8e031ced356399ccb734759bc3d269c15032c2b86998e5377d4018ffe0641d6"
      def install
        bin.install "gork"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/gork/releases/download/0.1.8/gork_Linux_arm.tar.gz"
      sha256 "7907017a419ec447280eb050c1a8372d4064d39e4f0d2df4d5a63ed23ab0c642"
      def install
        bin.install "gork"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/gork/releases/download/0.1.8/gork_Linux_arm64.tar.gz"
      sha256 "7b9f92674cd38e9a7b25283beebbd251e6b6f968c24c550049428840312c6f4b"
      def install
        bin.install "gork"
      end
    end
  end

  test do
    system "#{bin}/gork --version"
  end
end
