# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harsh < Formula
  desc "habit tracking for geeks. A minimalist CLI for examining your habits."
  homepage "https://github.com/wakatara/harsh"
  version "0.10.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/harsh/releases/download/v0.10.17/harsh_Darwin_x86_64.tar.gz"
      sha256 "442f6983474bc1dfd97fb54dfd361926689e7679260db7df7b485eb5b741c985"

      def install
        bin.install "harsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/harsh/releases/download/v0.10.17/harsh_Darwin_arm64.tar.gz"
      sha256 "f60033a6a1c1d446f9f0dfea6be982bd271e323d691ef5e196628f14d3f404d3"

      def install
        bin.install "harsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wakatara/harsh/releases/download/v0.10.17/harsh_Linux_x86_64.tar.gz"
        sha256 "2b44776cda703039fd62412bdee7e4b01cfd226a29f4a7cc67fec06fd744a495"

        def install
          bin.install "harsh"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wakatara/harsh/releases/download/v0.10.17/harsh_Linux_arm64.tar.gz"
        sha256 "cb01fdeb09b4de330b0156aaa83bcc5f18bd438d128b3b61648cbc3f68e0c294"

        def install
          bin.install "harsh"
        end
      end
    end
  end

  test do
    system "#{bin}/harsh --version"
  end
end
