# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ice < Formula
  desc "Comet sublimation modeling tool - calculates equilibrium temperature and sublimation rates for volatile ices"
  homepage "https://github.com/wakatara/ice9"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/ice9/releases/download/0.1.0/ice9_Darwin_x86_64.tar.gz"
      sha256 "c9341a0cdcc3d25a28413a82d5a889934b7ed4c0cca4776ccff38e13253e9515"

      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/ice9/releases/download/0.1.0/ice9_Darwin_arm64.tar.gz"
      sha256 "b3af55b2a63428d61d1f00c77381252af43be45a1c0dd3fc6e629d063266fff1"

      def install
        bin.install "ice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.1.0/ice9_Linux_x86_64.tar.gz"
      sha256 "eab21e393bcab4e9fd2285aa4216a077507b6d5a8f80faa7ff36b787080925ed"
      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.1.0/ice9_Linux_arm64.tar.gz"
      sha256 "fb381892cc0a7aae8450d16ecb8b107fbdceabe7933df85877fd8d226ee88b80"
      def install
        bin.install "ice"
      end
    end
  end

  test do
    system "#{bin}/ice version"
  end
end
