# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ice < Formula
  desc "Comet sublimation modeling tool - calculates equilibrium temperature and sublimation rates for volatile ices"
  homepage "https://github.com/wakatara/ice9"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/ice9/releases/download/0.2.0/ice9_Darwin_x86_64.tar.gz"
      sha256 "106dbcd77b957809c461703d97430529ab8515915bc935c22a1aa0f949a8fb19"

      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/ice9/releases/download/0.2.0/ice9_Darwin_arm64.tar.gz"
      sha256 "2756f8825fdfeaad607a89b43514f718b13913c76219a6dcc6455e9ec045bf45"

      def install
        bin.install "ice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.2.0/ice9_Linux_x86_64.tar.gz"
      sha256 "0e261a2f60a1494e124c919add90d5ab3b743ceb3c0b32f5a68c555ccdcdc1a6"
      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.2.0/ice9_Linux_arm64.tar.gz"
      sha256 "279ac41c4f232ccce6caaa0ebc435942d904926c2e1de02034ab6ca6f947da28"
      def install
        bin.install "ice"
      end
    end
  end

  test do
    system "#{bin}/ice version"
  end
end
