# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ice9 < Formula
  desc "Comet sublimation modeling tool - calculates equilibrium temperature and sublimation rates for volatile ices"
  homepage "https://github.com/wakatara/ice9"
  version "0.4.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.5/ice9_Darwin_x86_64.tar.gz"
      sha256 "940ad22803f5e0a6a5996c0ee8bc0f1c14b39120feafd69c03a55a7ed87dc921"

      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.5/ice9_Darwin_arm64.tar.gz"
      sha256 "5139ae2434fc39dc5bdc50aa1d303195d61ed852143c6850010a5d262984426c"

      def install
        bin.install "ice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.5/ice9_Linux_x86_64.tar.gz"
      sha256 "92196626fdca73b1427314f244147250dcf4e4014f0fb10de66e7fda6465f5fa"
      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.5/ice9_Linux_arm64.tar.gz"
      sha256 "a2b528561b194c10fff24ab6094472f319051c556d15099aad767466b2bfcdc7"
      def install
        bin.install "ice"
      end
    end
  end

  test do
    system "#{bin}/ice version"
  end
end
