# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ice9 < Formula
  desc "Comet sublimation modeling tool - calculates equilibrium temperature and sublimation rates for volatile ices"
  homepage "https://github.com/wakatara/ice9"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.4/ice9_Darwin_x86_64.tar.gz"
      sha256 "07b2114385b581e92b37aa5fc608454f3b7388987420ea577f7d87b1d679ce54"

      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.4/ice9_Darwin_arm64.tar.gz"
      sha256 "3fb9bdb63cff3d5dc9ad0f14b49ccb71859c73e421e3071350352ea04efb07c5"

      def install
        bin.install "ice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.4/ice9_Linux_x86_64.tar.gz"
      sha256 "c40ce113e8d17176544217597a0482e82cf078ea79b414e7570d0813eab83e48"
      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/v0.4.4/ice9_Linux_arm64.tar.gz"
      sha256 "c45a913de1bce7733c9a09d626288f04a13eec5178216445e5e165554571ebde"
      def install
        bin.install "ice"
      end
    end
  end

  test do
    system "#{bin}/ice version"
  end
end
