# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ice9 < Formula
  desc "Comet sublimation modeling tool - calculates equilibrium temperature and sublimation rates for volatile ices"
  homepage "https://github.com/wakatara/ice9"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wakatara/ice9/releases/download/0.4.1/ice9_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "f19e0445bc129c3ca873e77815ec3bfa2273df0a22413813c4c0efa4cec66d34"

      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wakatara/ice9/releases/download/0.4.1/ice9_0.4.1_Darwin_arm64.tar.gz"
      sha256 "e00f02867b6592d900ea01d0202502239034ab836b4c303d5b49b576f78e9402"

      def install
        bin.install "ice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.4.1/ice9_0.4.1_Linux_x86_64.tar.gz"
      sha256 "2257bd062e432039f20c6a892783ccd525a7f45a93fb2dd9aeb5a515dfe2b838"
      def install
        bin.install "ice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wakatara/ice9/releases/download/0.4.1/ice9_0.4.1_Linux_arm64.tar.gz"
      sha256 "796388f8d45f8ea3952c6028fa82b8e3ec03dced0c07d77df0927badef8f4f08"
      def install
        bin.install "ice"
      end
    end
  end

  test do
    system "#{bin}/ice version"
  end
end
